# Generated by Django 3.1.7 on 2021-03-13 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('ava', 'Available'), ('not', 'Not available')], default='ava', max_length=3)),
                ('model', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
