# Generated by Django 3.1.7 on 2021-03-11 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('start_data', models.DateTimeField(default=datetime.date(2021, 3, 11))),
                ('start_location', models.CharField(max_length=100)),
                ('end_location', models.CharField(max_length=100)),
            ],
        ),
    ]
