# Generated by Django 3.1.7 on 2021-03-11 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20210311_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='start_data',
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
